from enum import Enum


class Emoji(Enum):
    PLAY = "*play*"
    FACE_HEARTS = "<3"
    FACE_TONGUE = ":P"
    FACE_SMILE = ":D"
    FACE_CRY_LAUGH = "xD"
    FACE_HALO = "=D"
    FACE_NERDY = "*nerdy*"
    FACE_TEAR = "*cry*"
    FACE_SAD = ":("
    FACE_ZZZ = "*sleep*"
    FACE_ROLLING_EYES = "*rolling-eyes*"
    FILM = "*watch*"
    POPCORN = "*popcorn*"
    FACE_KISS = "*kiss*"
    FACE_BLUSH_SMILE = "*smiling*"
    FACE_THINK = "*thinking*"
    THUMBS_UP = ":thumbsup:"
    THUMBS_DOWN = ":thumbsdown:"
    PIZZA = "*pizza*"
    PARTY = "*party*"
    FOLDED_HANDS = "*folded-hands*"
    FIRE = "*hot*"
